//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int empno { get; set; }
        public string empname { get; set; }
        public string job { get; set; }
        public Nullable<int> supervisor { get; set; }
        public Nullable<int> deptno { get; set; }
        public Nullable<int> salaire { get; set; }
        public Nullable<System.DateTime> datenaiss { get; set; }
        public Nullable<bool> sexe { get; set; }
        public string civilite { get; set; }
    
        public virtual departement departement { get; set; }
    }
}
